### PR TITLE
Add a warning to README to warn users of needing 32 bit vulkan loader.

### PR DESCRIPTION
**Pull request by acedogblast**
Added a warning in the README to warn users of needing 32 bit vulkan loader.
I was trying to test out d9vk on some games I have. All of them crashed immediately with d9vk without a 32 bit vulkan loader. Since most dx9 games are 32 bit this warning should be helpful.

### CODE REVIEW

**Comment by Kerrung** [comment]
@acedogblast and lib32-vulkan-icd-loader on Arch Linux.

**Comment by acedogblast** [comment]
@Kerrung Is this the right command for Arch?
`sudo pacman -S lib32-vulkan-icd-loader`

**Comment by Kerrung** [comment]
> sudo pacman -S lib32-vulkan-icd-loader

$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Kerrung** [comment]
AMD Radeon GPU users also need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users also need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

**Comment by Kerrung** [comment]
> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

AMD Radeon GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Kerrung** [comment]
> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

https://wiki.archlinux.org/index.php/Pacman#Installing_packages
Warning: When installing packages in Arch, avoid refreshing the package list without upgrading the system (for example, when a package is no longer found in the official repositories). In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues.

AMD Radeon GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Kerrung** [comment]
> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

https://wiki.archlinux.org/index.php/Pacman#Installing_packages
Warning: When installing packages in Arch, avoid refreshing the package list without upgrading the system (for example, when a package is no longer found in the official repositories).
In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues.

AMD Radeon GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Kerrung** [comment]
> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

https://wiki.archlinux.org/index.php/Pacman#Installing_packages
Warning: When installing packages in Arch, avoid refreshing the package list without upgrading the system (for example, when a package is no longer found in the official repositories).
In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues. So, not ArchWiki recomend to use pacman -S, and instead we should to use
pacman -Syu package_name

AMD Radeon GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Kerrung** [comment]
> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

https://wiki.archlinux.org/index.php/Pacman#Installing_packages
Warning: When installing packages in Arch, avoid refreshing the package list without upgrading the system (for example, when a package is no longer found in the official repositories).
In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues. So, not ArchWiki recomend to use pacman -S, and instead we should to use
pacman -Syu package_name

https://wiki.archlinux.org/index.php/Vulkan
AMD Radeon GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Kerrung** [comment]
> @Kerrung Is this the right command for Arch?
> `sudo pacman -S lib32-vulkan-icd-loader`

https://wiki.archlinux.org/index.php/Pacman#Installing_packages
Warning: When installing packages in Arch, avoid refreshing the package list without upgrading the system (for example, when a package is no longer found in the official repositories).
In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues. So, ArchWiki not recomend to use pacman -S, and instead we should to use
pacman -Syu package_name

https://wiki.archlinux.org/index.php/Vulkan
AMD Radeon GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-radeon vulkan-radeon.
Intel GPU users need to install:
$ sudo pacman -Syu lib32-vulkan-icd-loader vulkan-icd-loader lib32-vulkan-intel vulkan-intel
Nvidia GPU users need to install:
$ sudo pacman -Syu nvidia nvidia-utils lib32-nvidia-utils lib32-vulkan-icd-loader vulkan-icd-loader

**Comment by Riesi** [comment]
I dont want to dampen your enthusiasm, but this is already part of the DXVK wiki.
https://github.com/doitsujin/dxvk/wiki/Common-issues#vulkan-errors

**Pull request closed without merging**
