### PR TITLE
Support for hack formats R16 & AL16

### PR DESCRIPTION
**Pull request by K0bin**
AC Revelation appears to need those. #154
Wine claims that Windows driver don't support those formats but the comment that says that was written 8 years ago. Either way, this should at least silence the warnings and its rather trivial.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Surely the swizzle for AL16 should be
`        { VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_R,
VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G }};`

and R16:
`        { VK_COMPONENT_SWIZZLE_R,   VK_COMPONENT_SWIZZLE_ONE,
VK_COMPONENT_SWIZZLE_ONE, VK_COMPONENT_SWIZZLE_ONE }};`

**Comment by Joshua-Ashton** [comment]
Also... You're using UINT formats and not UNORMs. This too is incorrect.

**Comment by K0bin** [comment]
Changed it.

**Comment by K0bin** [comment]
So, should I rebase this?

**Pull request closed without merging**
